version: '3'
services:
  nginx:
    build: ./nginx
    depends_on:
      - app
      - api
    ports:
      - "80:80"
    networks:
      - my_net
  app:
    build: ./recognizer
    networks:
      - my_net
  api:
    build: ./api
    volumes:
      - my_volume:/app/uploads
    networks:
      - my_net
  phantom:
    build: ./phantom
    volumes:
      - my_volume:/api/uploads
    networks:
      - my_net

volumes:
  my_volume:
networks:
  my_net:
    driver: bridge
